name: ClusterFuzzLite batch fuzzing
on:
  pull_request:
    paths:
      - '**'
  push:
    branches:
      - main  # Use your actual default branch here.
  schedule:
    - cron: '0 0/6 * * *'  # Every 6th hour. Change this to whatever is suitable.
jobs:
